steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/greatsword-v3', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/greatsword-v3']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'greatsword-v3', '--image', 'gcr.io/$PROJECT_ID/greatsword-v3', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
images:
  - 'gcr.io/$PROJECT_ID/greatsword-v3'
